from __future__ import annotations

DATASET_ID = "stanforddams/biglocal"
DEFAULT_REVISION = "4e9cd487de2b4781bc40b39a92295b0ee6827034"
DEFAULT_SPLIT = "train"
PARSER_VERSION = "1.0.0"

MISSING_SENTINELS = frozenset({"", "n/a", "na", "none", "null", "not found", "unknown"})

US_REGION_CODES = frozenset(
    {
        "AK",
        "AL",
        "AR",
        "AS",
        "AZ",
        "CA",
        "CO",
        "CT",
        "DC",
        "DE",
        "FL",
        "FM",
        "GA",
        "GU",
        "HI",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MA",
        "MD",
        "ME",
        "MH",
        "MI",
        "MN",
        "MO",
        "MP",
        "MS",
        "MT",
        "NC",
        "ND",
        "NE",
        "NH",
        "NJ",
        "NM",
        "NV",
        "NY",
        "OH",
        "OK",
        "OR",
        "PA",
        "PR",
        "PW",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VA",
        "VI",
        "VT",
        "WA",
        "WI",
        "WV",
        "WY",
    }
)

REQUIRED_REFERENCE_FIELDS = (
    "url",
    "title",
    "subtitle",
    "topics",
    "date_raw",
    "date_normalized",
    "date_last_updated",
    "location_full_text",
    "city",
    "state",
    "full_text",
    "image_urls",
    "scraped_at",
    "blurb_list",
    "updated_date",
)
